### ISSUE TITLE
Revoking Tyk Keys

### ISSUE THREAD

**Issue by TimMcCauley** [liip/wp-tyk-dev-portal#6]
Thank you for this great plugin. I am experiencing one issue regarding revoking keys. We are running tyk hybrid with your plugin and the behaviour of requesting keys works flawlessly. Deleting however either results in:

a) tyk removes the key for good (expected behaviour) or 
b) tyk removes the key and recreates it again

As I can tell the behaviour is random and we can't determine a pattern. We don't want b) to happen really. 

Did you run into this problem? I have a support ticket running on tyk but maybe you know the answer already.. ;-)

```
time="Dec 11 14:07:20" level=info msg="Deleted hashed key." key=.. status=ok
time="Dec 11 14:08:04" level=info msg="Recreating session for key: 58d904a497c67e00015.."
time="Dec 11 14:08:09" level=info msg="Deleted hashed key." key=.. status=ok
time="Dec 11 14:08:17" level=info msg="Recreating session for key: 58d904a497c67e00015.."
time="Dec 11 14:10:03" level=info msg="Deleted hashed key." key=.. status=ok
time="Dec 11 14:10:09" level=info msg="Deleted hashed key." key=.. status=ok
time="Dec 11 14:10:09" level=warning msg="Key not found in storage engine" err="Key not found" inbound-key="****4b73"
time="Dec 11 14:10:09" level=info msg="Attempted access with non-existent key." key=58d904a497c67e0.. origin=XY path="/isochrones"
time="Dec 11 14:10:09" level=error msg="request error: Key not authorised" api_id=.. org_id=.. path="/" server_name= user_id= user_ip=".."
```

These are the endpoints I added to the config:

```
/** Tyk.io setup */
define( 'TYK_CONFIGURATION', 'hybrid' ); // the tyk setup you're using ('cloud', 'on-premise' or 'hybrid')
define( 'TYK_API_ENDPOINT', 'https://admin.cloud.tyk.io/api/' ); // or the url to your Tyk installation
define( 'TYK_API_KEY', 'access_token..' ); // access token you created for the management user
define( 'TYK_AUTO_APPROVE_KEY_REQUESTS', true ); // read more below // these are only needed when TYK_CONFIGURATION is 'on-premise' or 'hybrid'
define( 'TYK_GATEWAY_URL', 'http://IP_TO_GATEWAY:8080/tyk' ); // the url of your tyk gateway
define( 'TYK_GATEWAY_SECRET', 'secret..' ); // the gateway secret // optional
define( 'TYK_FORCE_DISABLE_BOOTSTRAP', true ); // do not include bootstrap styles
```
If you have any idea what's going on here, I'd be truly grateful ;)

**Comment by 0x616469** [comment]
Strange behaviour indeed. We also use the plugin with Tyk hybrid but as far as I can remember we never came across this issue. 
When you say "tyk removes the key and recreates it again" is that literally what happens? The same key is created again? I don't see how that could happen. The only thing that I can imagine is that the call to the dashboard api to delete the key fails and the key is only deleted from the gateway. In this case the gateway would of course just fetch the key from dashboard again when the next request with this key is made. 
To dig a bit deeper you'd probably have to add some logging in https://github.com/liip/wp-tyk-dev-portal/blob/master/classes/dashboard_ajax_provider.php#L107

HTH

**Comment by TimMcCauley** [comment]
Thank you for the info @0x616469 - I solved it by sending two requests - the first to:

`https://admin.cloud.tyk.io/api/apis/api_id/keys/key_id` - before and by default it was

```
$response = $this->api->delete(sprintf('/portal/developers/key/%s/%s/%s',
				$this->policy,
				$this->hash,
				$this->user->get_tyk_id()
				));
```

and afterwards another one to, by default in `token.php`

`http://ip_to_tyk_container:8080/tyk/keys/key_id?hashed=1`

Can you confirm?

**Comment by chlab** [comment]
> and afterwards another one to, by default in token.php
http://ip_to_tyk_container:8080/tyk/keys/key_id?hashed=1

By `ip_to_tyk_container` you mean your gateway node? If so, you shouldn't have to do that manually. This sounds more like the Tyk cloud not propagating your token revokal to the gateway node, although I may be mistaken. We had quite a bit of trouble with the cloud not syncing everything to the gateway nodes.

**Comment by TimMcCauley** [comment]
I mean the gateway node, correct. If I send it to `https://admin.cloud.tyk.io/api/apis/..?` it is automatically propagated to the gateway nodes of tyk. It only doesn't work if I use the default url `https://admin.cloud.tyk.io/api/portal/developers..` for deletion. Consider this as closed, thank you for your input.
