### ISSUE TITLE
Not working with Wordpress 4.9.2

### ISSUE THREAD

**Issue by DamianMalik** [liip/wp-tyk-dev-portal#7]
After installation and activation, nothing happens. 

> Activation of this plugin should have triggered the creation of the user role „Developer“ an the page „Developer Dashboard“. Note that the „Developer Dashboard“ page must have the slug „dev-dashboard“ otherwise the scripts won’t be included.

Clicking at "User" - <myName>, there is nothing. What do you mean with "slug"? - Give example or better description.

**Comment by chlab** [comment]
First: keep in mind that this plugin is free and not officially supported. _Please_ and _thank you_ go a long way.

- Go to "Pages" and check if there is a Page called "Developer Dashboard". If not, you can create it manually. The slug of the page should be set to `dev-dashboard`. Slug is a WordPress (and web development) term, you can find lots of info on google. [Here's a good article on it](https://kinsta.com/knowledgebase/wordpress-slug/) for example.
- As for the "Developer" role - this isn't that relevant. It's only a help for you to differentiate between which users registered via your dev portal and which ones are regular WordPress users. You won't see any of these users under the "Users" section until you register as a developer in your WP frontend.

**Comment by DamianMalik** [comment]
Ahhh... there ...  okay, I've found it. Thanks a lot.
